/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.5
 * Generated at: 2017-11-28 13:04:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import in.vamsoft.model.Question;

public final class taketest_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1510900016000L));
    _jspx_dependants.put("jar:file:/home/vamsoft/jk/VamTraining/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/TestEngine/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
    _jspx_dependants.put("/header.jsp", Long.valueOf(1511868618000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("in.vamsoft.model.Question");
    _jspx_imports_classes.add("java.util.List");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\" src=\"path_to/jquery.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"path_to/jquery.simplePagination.js\"></script>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<link type=\"text/css\" rel=\"stylesheet\"\n");
      out.write("\thref=\"path_to/simplePagination.css\" />\n");
      out.write("\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\tvar sessionTimeout = 300;\n");
      out.write("\n");
      out.write("\tfunction DisplaySessionTimeout() {\n");
      out.write("\t\twindow.history.go(+1);\n");
      out.write("\t\tsessionTimeout = sessionTimeout - 1;\n");
      out.write("\t\t//document.getElementById(\"val\").innerHTML=sessionTimeout;\n");
      out.write("\n");
      out.write("\t\t//if session is not less than 0\n");
      out.write("\t\tif (sessionTimeout >= 0) {\n");
      out.write("\t\t\t//call the function again after 1 minute delay\n");
      out.write("\n");
      out.write("\t\t\twindow.setTimeout(\"DisplaySessionTimeout()\", 1000);\n");
      out.write("\t\t} else {\n");
      out.write("\t\t\t//show message box\n");
      out.write("\t\t\t//document.getElementById(\"val\").innerHTML=\"TIME OUT\";\n");
      out.write("\t\t\talert(\"Your current Session is over.\");\n");
      out.write("\t\t\tsetTimeout(document.form.sub.click());\n");
      out.write("\t\t}\n");
      out.write("\t}\n");
      out.write("\n");
      out.write("\tvar seconds = 0\n");
      out.write("\tvar minutes = 5\n");
      out.write("\tdocument.form.time.value = '30'\n");
      out.write("\n");
      out.write("\tfunction display() {\n");
      out.write("\t\tif (seconds <= 0) {\n");
      out.write("\t\t\tseconds = 60\n");
      out.write("\t\t\tminutes -= 1\n");
      out.write("\t\t}\n");
      out.write("\t\tif (minutes <= -1) {\n");
      out.write("\t\t\tseconds = 0\n");
      out.write("\t\t\tminutes += 1\n");
      out.write("\t\t} else\n");
      out.write("\t\t\tseconds -= 1\n");
      out.write("\t\tdocument.getElementById(\"time\").innerHTML = minutes + \"M : \" + seconds\n");
      out.write("\t\t\t\t+ \" S\"\n");
      out.write("\t\tsetTimeout(\"display()\", 1000)\n");
      out.write("\t}\n");
      out.write("\n");
      out.write("\t$(function() {\n");
      out.write("\t\t$(\"#page\").pagination({\n");
      out.write("\t\t\titems : 8,\n");
      out.write("\t\t\titemsOnPage : 4,\n");
      out.write("\t\t\tcssStyle : 'light-theme'\n");
      out.write("\t\t});\n");
      out.write("\t});\n");
      out.write("</script>\n");
      out.write("<style type=\"text/css\">\n");
      out.write(".timer {\n");
      out.write("\tcolor: red;\n");
      out.write("\tfloat: right;\n");
      out.write("\tfont-size: 20px;\n");
      out.write("\tbackground-color: transparent;\n");
      out.write("\twidth: 100px;\n");
      out.write("\ttext-align: center;\n");
      out.write("\tbackground-color: transparent;\n");
      out.write("\tfont-size: 20px;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body onLoad=\"javascript:display();DisplaySessionTimeout();\">\n");
      out.write("\t");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("\thref=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\n");
      out.write("\n");
      out.write("<!-- jQuery library -->\n");
      out.write("<script\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\n");
      out.write("<script src=\"vendor/jquery-validation/dist/jquery.validate.min.js\"></script>\n");
      out.write("\n");
      out.write("<!-- Latest compiled JavaScript -->\n");
      out.write("<script\n");
      out.write("\tsrc=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\n");
      out.write("<style type=\"text/css\">\n");
      out.write(".navbar-inverse {\n");
      out.write("\tbackground: #00796B;\n");
      out.write("\tborder-bottom-color: #004D40;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".navbar-inverse .navbar-nav>li>a, .navbar-inverse .navbar-brand,\n");
      out.write("\t.navbar-inverse .navbar-nav>.dropdown>a .caret {\n");
      out.write("\tcolor: #fff;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".navbar-inverse .navbar-nav>.open>a, .navbar-inverse .navbar-nav>.open>a:hover,\n");
      out.write("\t.navbar-inverse .navbar-nav>.open>a:focus, .navbar-nav>li>.dropdown-menu\n");
      out.write("\t{\n");
      out.write("\tbackground: #4DB6AC;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".nav-pills\n");
      out.write(">\n");
      out.write("li\n");
      out.write(">\n");
      out.write("a\n");
      out.write(",\n");
      out.write("{\n");
      out.write("color\n");
      out.write(":\n");
      out.write(" \n");
      out.write("#303F9F\n");
      out.write(";\n");
      out.write("\n");
      out.write("\n");
      out.write("}\n");
      out.write(".nav>li>a:hover, .nav>li>a:focus {\n");
      out.write("\tbackground-color: #EEEEEE;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<div id=\"top-nav\" class=\"navbar navbar-inverse navbar-static-top\">\n");
      out.write("\t\t<div class=\"container-fluid\">\n");
      out.write("\t\t\t<div class=\"navbar-header\">\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\"\n");
      out.write("\t\t\t\t\tdata-target=\".navbar-collapse\">\n");
      out.write("\t\t\t\t\t<span class=\"icon-bar\"></span> <span class=\"icon-bar\"></span> <span\n");
      out.write("\t\t\t\t\t\tclass=\"icon-bar\"></span>\n");
      out.write("\t\t\t\t</button>\n");
      out.write("\t\t\t\t<a class=\"navbar-brand\" href=\"dashboard.jsp\">CompanyName</a>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"navbar-collapse collapse\">\n");
      out.write("\t\t\t\t<ul class=\"nav navbar-nav navbar-right\">\n");
      out.write("\t\t\t\t\t<li><i class=\"fa fa-user-circle\"></i><a>");
      out.print(session.getAttribute("name"));
      out.write("</a>\n");
      out.write("\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<li><a href=\"Login.html\"><i class=\"fa fa-sign-out\"></i>\n");
      out.write("\t\t\t\t\t\t\tLogout</a></li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<!-- /container -->\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
      out.write('\n');
      out.write('	');

	  List<Question> questions = (List<Question>) session.getAttribute("Questions");
	
      out.write("\n");
      out.write("\t<form name=\"form\" action=\"Results\">\n");
      out.write("\t\t<div class=\"col-sm-2\"></div>\n");
      out.write("\t\t<div class=\"col-sm-8\">\n");
      out.write("\t\t\t<label class=\"timer\" id=\"time\"></label>\n");
      out.write("\n");
      out.write("\t\t\t<form name=\"form1\" id=\"page\">\n");
      out.write("\t\t\t\t");

				  for (Question element : questions) {
				
      out.write("\n");
      out.write("\t\t\t\t<div style=\"margin-top:20px;font-style:bold;\">");
      out.print(element.getqNo());
      out.write('.');
      out.print(element.getQuestion());
      out.write("</div>\n");
      out.write("\t\t\t\t<div>\n");
      out.write("\t\t\t\t\t<input type=\"radio\" name=\"");
      out.print(element.getqNo());
      out.write("\" value=\"");
      out.print(element.getOp1());
      out.write('"');
      out.write('>');
      out.print(element.getOp1());
      out.write("<br>\n");
      out.write("\t\t\t\t\t<input type=\"radio\" name=\"");
      out.print(element.getqNo());
      out.write("\" value=\"");
      out.print(element.getOp2());
      out.write('"');
      out.write('>');
      out.print(element.getOp2());
      out.write("<br>\n");
      out.write("\t\t\t\t\t<input type=\"radio\" name=\"");
      out.print(element.getqNo());
      out.write("\" value=\"");
      out.print(element.getOp3());
      out.write('"');
      out.write('>');
      out.print(element.getOp3());
      out.write("<br>\n");
      out.write("\t\t\t\t\t<input type=\"radio\" name=\"");
      out.print(element.getqNo());
      out.write("\" value=\"");
      out.print(element.getOp4());
      out.write('"');
      out.write('>');
      out.print(element.getOp4());
      out.write("<br>\n");
      out.write("\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t");

				  }
				
      out.write("\n");
      out.write("\t\t\t</form>\n");
      out.write("\t\t\t<input type=\"submit\" name=\"sub\" value=\"submit\">\n");
      out.write("\t\t</div>\n");
      out.write("\t</form>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
